/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'MarkPerry' at '6/12/13 9:06 AM' with Gradle 1.9
 *
 * @author MarkPerry, @date 6/12/13 9:06 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
